### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by wuzer** [dafidxcode/piggy#1]
after add tgdata ，run code get error，
<img width="471" alt="image" src="https://github.com/user-attachments/assets/ff1509ca-0645-456c-84fe-d914a9a47643">

**Comment by dafidxcode** [comment]
Update script and after then pease use new python version, update & upgrade your package
Paste your cookies in akun.txt

**Comment by wuzer** [comment]
Thank you for your reply. macOS still reports this error after trying to pull the latest code. I repeated the process with an Android phone and it worked. It may be a problem with the python version of my macOS.
